version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  fileregister:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGODB_CONNECTION_URI: "mongodb://host.docker.internal"
