version: "3.9"
services:
  mongodb:
    image: mongo:latest@sha256:3ed24298a65470d4a3553621ecb96d53ea3fef14f2800411a01566536c3f966d
    ports:
      - "27017:27017"
  fileregister:
    build: .
    image: rtd-ms-file-register-fileregister:latest
    ports:
      - "8080:8080"
    environment:
      MONGODB_CONNECTION_URI: "mongodb://host.docker.internal"
      KAFKA_BROKER: "kafka:9092"
      KAFKA_RTD_PROJECTOR_BROKER: "kafka:9092"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - kafka
      - mongodb
  zookeeper:
    image: confluentinc/cp-zookeeper@sha256:4dc780642bfc5ec3a2d4901e2ff1f9ddef7f7c5c0b793e1e2911cbfb4e3a3214
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    container_name: zookeeper
  kafka:
    image: confluentinc/cp-kafka@sha256:620734d9fc0bb1f9886932e5baf33806074469f40e3fe246a3fdbb59309535fa
    hostname: kafka
    container_name: kafka
    ports:
      - "29095:29095"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
    depends_on:
      - zookeeper
