FROM ghcr.io/graalvm/graalvm-community:23.0.1-ol8-20241015@sha256:c9012a16ed8858f7701f38ab04ea02d711bc5edaf143941cb122f537d1d3e69d AS builder

WORKDIR /build
COPY . .

RUN ./mvnw clean package -Pnative -DskipTests

FROM ubuntu:noble-20241011@sha256:99c35190e22d294cdace2783ac55effc69d32896daaa265f0bbedbcde4fbe3e5 AS cve
COPY --from=builder /build/target/rtd-ms-file-register*.jar .

FROM ubuntu:noble-20241011@sha256:99c35190e22d294cdace2783ac55effc69d32896daaa265f0bbedbcde4fbe3e5 AS runtime

EXPOSE 8080

RUN useradd --uid 10000 runner
USER 10000

COPY --from=builder /build/target/rtd-ms-file-register .

ENTRYPOINT ["./rtd-ms-file-register"]
