version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  fileregister:
    build: .
    image: rtd-ms-file-register-fileregister:latest
    ports:
      - "8080:8080"
    environment:
      MONGODB_CONNECTION_URI: "mongodb://host.docker.internal"
      KAFKA_BROKER: "kafka:9092"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - kafka
      - mongodb
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    container_name: zookeeper
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "29095:29095"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
    depends_on:
      - zookeeper
