logging:
    level:
        root: INFO

---

spring:
    config:
        activate:
            on-profile: default
    data:
        mongodb:
            uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
            database: ${MONGODB_NAME:rtd}
    cloud:
        stream:
            kafka:
                binder:
                    configuration:
                        security.protocol: SASL_SSL
                        sasl.mechanism: PLAIN
            bindings:
                blobStorageConsumer-in-0: # name must match [handler name]-in-0
                    destination: rtd-platform-events
                    group: rtd-file-register-consumer-group
                    content-type: application/json
                    binder: blob-storage
                fileRegisterProjector-out-0:
                    destination: ${KAFKA_RTD_PROJECTOR_TOPIC:rtd-file-register-projector}
                    content-type: application/json
                    binder: eventhub-projector
            binders:
                eventhub-projector:
                    type: kafka
                    environment.spring.cloud.stream.kafka.binder:
                        auto-create-topics: false
                        brokers: ${KAFKA_RTD_PROJECTOR_BROKER:localhost:29095}
                        configuration.sasl.jaas.config: ${KAFKA_RTD_PROJECTOR_SASL_JAAS_CONFIG}
                        sync: true
                        requiredAcks: all
                blob-storage:
                    type: kafka
                    environment:
                        spring:
                            cloud:
                                stream:
                                    kafka:
                                        binder:
                                            auto-create-topics: false
                                            brokers: ${KAFKA_BROKER:localhost:29095}
                                            configuration:
                                                sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS}
                                            consumerProperties:
                                                key:
                                                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                                                value:
                                                    deserializer: org.apache.kafka.common.serialization.StringDeserializer

---

spring:
    config:
        activate:
            on-profile: dev
    data:
        mongodb:
            uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
            database: ${MONGODB_NAME:fileregister}
    cloud:
        stream:
            bindings:
                blobStorageConsumer-in-0: # name must match [handler name]-in-0
                    destination: rtd-platform-events
                    group: rtd-file-register-consumer-group
                    content-type: application/json
                    binder: blob-storage
                fileRegisterProjector-out-0:
                    destination: ${KAFKA_RTD_PROJECTOR_TOPIC:rtd-file-register-projector}
                    group: rtd-file-register-projector-consumer-group
                    content-type: application/json
                    binder: eventhub-projector
            binders:
                eventhub-projector:
                    type: kafka
                    environment.spring.cloud.stream.kafka.binder:
                        auto-create-topics: false
                        brokers: ${KAFKA_RTD_PROJECTOR_BROKER:localhost:29095}
                        consumerProperties:
                            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                blob-storage:
                    type: kafka
                    environment:
                        spring:
                            cloud:
                                stream:
                                    kafka:
                                        binder:
                                            auto-create-topics: false
                                            brokers: ${KAFKA_BROKER:localhost:29095}
                                            consumerProperties:
                                                key:
                                                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                                                value:
                                                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
