microservice-chart:
  image:
    repository: cstarpcommonacr.azurecr.io/rtdmsfileregister
    tag: latest
    pullPolicy: Always

  ingress:
    host: "prod01.rtd.internal.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  deployment:
      create: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  topologySpreadConstraints:
    create: true
    useDefaultConfiguration: true

  envSecret:
    aks-api-url: cstar-p-weu-prod01-aks-apiserver-url

  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 3
    pollingInterval: 30 # seconds
    cooldownPeriod: 10 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "60"

  keyvault:
    name: "cstar-p-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
