microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
    timeoutSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10
    timeoutSeconds: 10

  podAnnotations: { }

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /rtdmsfileregister/(.*)
    servicePort: 8080

  serviceAccount:
    name: "rtd-workload-identity" # Replace with your service account name if using workload identity
    # If using Azure Workload Identity, also add the azure section:
    azure:
      workloadIdentityClientId: "CHANGEME" # Insert your clientId here if needed

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  envSecret:
    MONGODB_CONNECTION_URI: mongo-db-connection-uri
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS: evh-rtd-platform-events-rtd-platform-events-sub-rtd
    KAFKA_RTD_PROJECTOR_SASL_JAAS_CONFIG: evh-rtd-file-register-projector-rtd-file-register-projector-producer-policy-rtd

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  externalConfigMapValues:
    rtd-fileregister:
      OPENTELEMETRY_LOG_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL

    rtd-file-register-projector-producer:
      KAFKA_RTD_PROJECTOR_TOPIC: KAFKA_RTD_PROJECTOR_TOPIC
      KAFKA_RTD_PROJECTOR_BROKER: KAFKA_RTD_PROJECTOR_BROKER

    rtd-blob-storage-events:
      KAFKA_TOPIC_BLOB_STORAGE_EVENTS: KAFKA_TOPIC_BLOB_STORAGE_EVENTS
      KAFKA_BROKER: KAFKA_BROKER_RTD
