microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/rtdmsfileregister
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.rtd.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  deployment:
    forceRedeploy: true

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url

  topologySpreadConstraints:
    create: true
    useDefaultConfiguration: true

  autoscaling:
    enable: true
    minReplica: 0
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 10 # seconds
    triggers:
      - type: cron
        metadata:
          # Required
          timezone: Europe/Rome  # The acceptable values would be a value from the IANA Time Zone Database.
          start: 0 7 * * *
          end: 0 21 * * *
          desiredReplicas: "1"
      - type: cpu
        metadata:
          type: Utilization
          value: "60"

  keyvault:
    name: "cstar-u-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
